/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStatisticsRouteImport } from './routes/_app.statistics'
import { Route as AppSnippetsRouteImport } from './routes/_app.snippets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConstellationRouteImport } from './routes/_app.constellation'
import { Route as AppCollectionsRouteImport } from './routes/_app.collections'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppSnippetsIndexRouteImport } from './routes/_app.snippets.index'
import { Route as AppSnippetsNewRouteImport } from './routes/_app.snippets.new'
import { Route as AppSnippetsIdRouteImport } from './routes/_app.snippets.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppSnippetsRoute = AppSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConstellationRoute = AppConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppSnippetsIndexRoute = AppSnippetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSnippetsRoute,
} as any)
const AppSnippetsNewRoute = AppSnippetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSnippetsRoute,
} as any)
const AppSnippetsIdRoute = AppSnippetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSnippetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/assistant': typeof AppAssistantRoute
  '/collections': typeof AppCollectionsRoute
  '/constellation': typeof AppConstellationRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/snippets': typeof AppSnippetsRouteWithChildren
  '/statistics': typeof AppStatisticsRoute
  '/snippets/$id': typeof AppSnippetsIdRoute
  '/snippets/new': typeof AppSnippetsNewRoute
  '/snippets/': typeof AppSnippetsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/assistant': typeof AppAssistantRoute
  '/collections': typeof AppCollectionsRoute
  '/constellation': typeof AppConstellationRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/statistics': typeof AppStatisticsRoute
  '/': typeof AppIndexRoute
  '/snippets/$id': typeof AppSnippetsIdRoute
  '/snippets/new': typeof AppSnippetsNewRoute
  '/snippets': typeof AppSnippetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/constellation': typeof AppConstellationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/export': typeof AppExportRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/snippets': typeof AppSnippetsRouteWithChildren
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/snippets/$id': typeof AppSnippetsIdRoute
  '/_app/snippets/new': typeof AppSnippetsNewRoute
  '/_app/snippets/': typeof AppSnippetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/signup'
    | '/assistant'
    | '/collections'
    | '/constellation'
    | '/dashboard'
    | '/export'
    | '/favorites'
    | '/settings'
    | '/snippets'
    | '/statistics'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/signup'
    | '/assistant'
    | '/collections'
    | '/constellation'
    | '/dashboard'
    | '/export'
    | '/favorites'
    | '/settings'
    | '/statistics'
    | '/'
    | '/snippets/$id'
    | '/snippets/new'
    | '/snippets'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/signup'
    | '/_app/assistant'
    | '/_app/collections'
    | '/_app/constellation'
    | '/_app/dashboard'
    | '/_app/export'
    | '/_app/favorites'
    | '/_app/settings'
    | '/_app/snippets'
    | '/_app/statistics'
    | '/_app/'
    | '/_app/snippets/$id'
    | '/_app/snippets/new'
    | '/_app/snippets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snippets': {
      id: '/_app/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof AppSnippetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/constellation': {
      id: '/_app/constellation'
      path: '/constellation'
      fullPath: '/constellation'
      preLoaderRoute: typeof AppConstellationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snippets/': {
      id: '/_app/snippets/'
      path: '/'
      fullPath: '/snippets/'
      preLoaderRoute: typeof AppSnippetsIndexRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
    '/_app/snippets/new': {
      id: '/_app/snippets/new'
      path: '/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof AppSnippetsNewRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
    '/_app/snippets/$id': {
      id: '/_app/snippets/$id'
      path: '/$id'
      fullPath: '/snippets/$id'
      preLoaderRoute: typeof AppSnippetsIdRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
  }
}

interface AppSnippetsRouteChildren {
  AppSnippetsIdRoute: typeof AppSnippetsIdRoute
  AppSnippetsNewRoute: typeof AppSnippetsNewRoute
  AppSnippetsIndexRoute: typeof AppSnippetsIndexRoute
}

const AppSnippetsRouteChildren: AppSnippetsRouteChildren = {
  AppSnippetsIdRoute: AppSnippetsIdRoute,
  AppSnippetsNewRoute: AppSnippetsNewRoute,
  AppSnippetsIndexRoute: AppSnippetsIndexRoute,
}

const AppSnippetsRouteWithChildren = AppSnippetsRoute._addFileChildren(
  AppSnippetsRouteChildren,
)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppConstellationRoute: typeof AppConstellationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportRoute: typeof AppExportRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSnippetsRoute: typeof AppSnippetsRouteWithChildren
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppConstellationRoute: AppConstellationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportRoute: AppExportRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSnippetsRoute: AppSnippetsRouteWithChildren,
  AppStatisticsRoute: AppStatisticsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
