/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSnippetsRouteImport } from './routes/admin.snippets'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminIaSystemeRouteImport } from './routes/admin.ia-systeme'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AppSnippetsRouteImport } from './routes/_app.snippets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConstellationRouteImport } from './routes/_app.constellation'
import { Route as AppCollectionsRouteImport } from './routes/_app.collections'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppSnippetsIndexRouteImport } from './routes/_app.snippets.index'
import { Route as AppCollectionsIndexRouteImport } from './routes/_app.collections.index'
import { Route as AppSnippetsNewRouteImport } from './routes/_app.snippets.new'
import { Route as AppSnippetsIdRouteImport } from './routes/_app.snippets.$id'
import { Route as AppCollectionsIdRouteImport } from './routes/_app.collections.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSnippetsRoute = AdminSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaSystemeRoute = AdminIaSystemeRouteImport.update({
  id: '/ia-systeme',
  path: '/ia-systeme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AppSnippetsRoute = AppSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConstellationRoute = AppConstellationRouteImport.update({
  id: '/constellation',
  path: '/constellation',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppSnippetsIndexRoute = AppSnippetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSnippetsRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCollectionsRoute,
} as any)
const AppSnippetsNewRoute = AppSnippetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSnippetsRoute,
} as any)
const AppSnippetsIdRoute = AppSnippetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSnippetsRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCollectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/assistant': typeof AppAssistantRoute
  '/collections': typeof AppCollectionsRouteWithChildren
  '/constellation': typeof AppConstellationRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/snippets': typeof AppSnippetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/ia-systeme': typeof AdminIaSystemeRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/snippets': typeof AdminSnippetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/snippets/$id': typeof AppSnippetsIdRoute
  '/snippets/new': typeof AppSnippetsNewRoute
  '/collections/': typeof AppCollectionsIndexRoute
  '/snippets/': typeof AppSnippetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/assistant': typeof AppAssistantRoute
  '/constellation': typeof AppConstellationRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/favorites': typeof AppFavoritesRoute
  '/settings': typeof AppSettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/ia-systeme': typeof AdminIaSystemeRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/snippets': typeof AdminSnippetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/snippets/$id': typeof AppSnippetsIdRoute
  '/snippets/new': typeof AppSnippetsNewRoute
  '/collections': typeof AppCollectionsIndexRoute
  '/snippets': typeof AppSnippetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/collections': typeof AppCollectionsRouteWithChildren
  '/_app/constellation': typeof AppConstellationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/export': typeof AppExportRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/snippets': typeof AppSnippetsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/ia-systeme': typeof AdminIaSystemeRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/snippets': typeof AdminSnippetsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/snippets/$id': typeof AppSnippetsIdRoute
  '/_app/snippets/new': typeof AppSnippetsNewRoute
  '/_app/collections/': typeof AppCollectionsIndexRoute
  '/_app/snippets/': typeof AppSnippetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/signup'
    | '/assistant'
    | '/collections'
    | '/constellation'
    | '/dashboard'
    | '/export'
    | '/favorites'
    | '/settings'
    | '/snippets'
    | '/admin/audit'
    | '/admin/ia-systeme'
    | '/admin/roles'
    | '/admin/snippets'
    | '/admin/users'
    | '/admin/'
    | '/collections/$id'
    | '/snippets/$id'
    | '/snippets/new'
    | '/collections/'
    | '/snippets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/signup'
    | '/assistant'
    | '/constellation'
    | '/dashboard'
    | '/export'
    | '/favorites'
    | '/settings'
    | '/admin/audit'
    | '/admin/ia-systeme'
    | '/admin/roles'
    | '/admin/snippets'
    | '/admin/users'
    | '/admin'
    | '/collections/$id'
    | '/snippets/$id'
    | '/snippets/new'
    | '/collections'
    | '/snippets'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/signup'
    | '/_app/assistant'
    | '/_app/collections'
    | '/_app/constellation'
    | '/_app/dashboard'
    | '/_app/export'
    | '/_app/favorites'
    | '/_app/settings'
    | '/_app/snippets'
    | '/admin/audit'
    | '/admin/ia-systeme'
    | '/admin/roles'
    | '/admin/snippets'
    | '/admin/users'
    | '/admin/'
    | '/_app/collections/$id'
    | '/_app/snippets/$id'
    | '/_app/snippets/new'
    | '/_app/collections/'
    | '/_app/snippets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/snippets': {
      id: '/admin/snippets'
      path: '/snippets'
      fullPath: '/admin/snippets'
      preLoaderRoute: typeof AdminSnippetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia-systeme': {
      id: '/admin/ia-systeme'
      path: '/ia-systeme'
      fullPath: '/admin/ia-systeme'
      preLoaderRoute: typeof AdminIaSystemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/snippets': {
      id: '/_app/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof AppSnippetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/constellation': {
      id: '/_app/constellation'
      path: '/constellation'
      fullPath: '/constellation'
      preLoaderRoute: typeof AppConstellationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snippets/': {
      id: '/_app/snippets/'
      path: '/'
      fullPath: '/snippets/'
      preLoaderRoute: typeof AppSnippetsIndexRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
    '/_app/collections/': {
      id: '/_app/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppCollectionsRoute
    }
    '/_app/snippets/new': {
      id: '/_app/snippets/new'
      path: '/new'
      fullPath: '/snippets/new'
      preLoaderRoute: typeof AppSnippetsNewRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
    '/_app/snippets/$id': {
      id: '/_app/snippets/$id'
      path: '/$id'
      fullPath: '/snippets/$id'
      preLoaderRoute: typeof AppSnippetsIdRouteImport
      parentRoute: typeof AppSnippetsRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppCollectionsRoute
    }
  }
}

interface AppCollectionsRouteChildren {
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
}

const AppCollectionsRouteChildren: AppCollectionsRouteChildren = {
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
}

const AppCollectionsRouteWithChildren = AppCollectionsRoute._addFileChildren(
  AppCollectionsRouteChildren,
)

interface AppSnippetsRouteChildren {
  AppSnippetsIdRoute: typeof AppSnippetsIdRoute
  AppSnippetsNewRoute: typeof AppSnippetsNewRoute
  AppSnippetsIndexRoute: typeof AppSnippetsIndexRoute
}

const AppSnippetsRouteChildren: AppSnippetsRouteChildren = {
  AppSnippetsIdRoute: AppSnippetsIdRoute,
  AppSnippetsNewRoute: AppSnippetsNewRoute,
  AppSnippetsIndexRoute: AppSnippetsIndexRoute,
}

const AppSnippetsRouteWithChildren = AppSnippetsRoute._addFileChildren(
  AppSnippetsRouteChildren,
)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCollectionsRoute: typeof AppCollectionsRouteWithChildren
  AppConstellationRoute: typeof AppConstellationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportRoute: typeof AppExportRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSnippetsRoute: typeof AppSnippetsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCollectionsRoute: AppCollectionsRouteWithChildren,
  AppConstellationRoute: AppConstellationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportRoute: AppExportRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSnippetsRoute: AppSnippetsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminIaSystemeRoute: typeof AdminIaSystemeRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSnippetsRoute: typeof AdminSnippetsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminIaSystemeRoute: AdminIaSystemeRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSnippetsRoute: AdminSnippetsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
